# Generated by Django 4.1.5 on 2023-02-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
