# Generated by Django 4.1.5 on 2023-02-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_candidate_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experince',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='opening',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
