# Generated by Django 4.1.5 on 2023-02-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_jobs_experince_alter_jobs_opening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='requirment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
