# Generated by Django 4.1.5 on 2023-02-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_jobs_requirment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
