# Generated by Django 4.1.5 on 2023-03-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
